<!DOCTYPE html>
<html lang="en"><head>
<script src="Introduction_to_Meta-Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Introduction_to_Meta-Analysis_files/libs/quarto-html/tabby.min.js"></script>
<script src="Introduction_to_Meta-Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Introduction_to_Meta-Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Introduction_to_Meta-Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Introduction_to_Meta-Analysis_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Introduction_to_Meta-Analysis_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Matthew Grainger">
  <title>Introduction to Meta-Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Introduction_to_Meta-Analysis_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Introduction_to_Meta-Analysis_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="Introduction_to_Meta-Analysis_files/libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link rel="stylesheet" href="juno.css">
  <link href="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introduction to Meta-Analysis</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Matthew Grainger 
</div>
</div>
</div>

</section>
<section id="what-is-meta-analysis" class="slide level2">
<h2>What is Meta-Analysis?</h2>
<ul>
<li><p>Meta-analysis is a statistical technique to combine results from multiple studies to get a clearer, more reliable picture</p></li>
<li><p>Say we want to know whether grazing reduces plant biodiversity. Studies disagree—some show decreases, some no effect, some even increases. Meta-analysis helps us quantify the overall trend</p></li>
</ul>
</section>
<section id="why-meta-analysis" class="slide level2">
<h2>Why Meta-Analysis?</h2>
<ul>
<li><p>Handles variation across studies</p></li>
<li><p>Can improve power and precision</p></li>
<li><p>Helps move beyond “vote-counting” (i.e., tallying +/– effects)</p></li>
</ul>
</section>
<section id="what-is-vote-counting" class="slide level2">
<h2>What is Vote-counting</h2>

<img data-src="images/clipboard-163317285.png" class="r-stretch"></section>
<section id="section" class="slide level2">
<h2></h2>

<img data-src="images/clipboard-688738285.png" class="r-stretch"></section>
<section id="section-1" class="slide level2">
<h2></h2>

<img data-src="images/clipboard-3885116124.png" class="r-stretch"></section>
<section>
<section id="core-concepts" class="title-slide slide level1 center">
<h1>Core concepts</h1>

</section>
<section id="effect-size" class="slide level2">
<h2>Effect size</h2>
<ul>
<li><strong>Effect size</strong> – <em>“A standardised way to compare results (e.g., log response ratio).”</em></li>
</ul>
<p><a href="https://matthewbjane.quarto.pub/Guide-to-Effect-Sizes-and-Confidence-Intervals.pdf" title="Detailed overview of different effect sizes">Effect sizes</a> are key to synthesising study results in meta-analysis, as they provide a standardised way of comparing findings across studies. Common effect sizes include the standardised mean difference (Hedges’ g in ecology), correlation coefficient, and log-transformed response ratio (lnRR).</p>
</section>
<section id="effect-size---smd" class="slide level2">
<h2>Effect size - SMD</h2>
<p>We have data from six fictional studies that examined species abundance before and after restoration efforts. The dataset includes: - Sample sizes before and after restoration (<code>n1</code> and <code>n2</code>). - Mean species abundance before and after (<code>m1</code> and <code>m2</code>). - Standard deviations of abundance before and after (<code>sd1</code> and <code>sd2</code>).</p>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>N (Before)</th>
<th>N (After)</th>
<th>Mean (B)</th>
<th>Mean (A)</th>
<th>SD (B)</th>
<th>SD (A)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smith_2015</td>
<td>30</td>
<td>28</td>
<td>5.2</td>
<td>3.9</td>
<td>1.1</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>Johnson_2017</td>
<td>50</td>
<td>48</td>
<td>6.1</td>
<td>5.4</td>
<td>1.3</td>
<td>1.1</td>
</tr>
<tr class="odd">
<td>Lee_2018</td>
<td>45</td>
<td>44</td>
<td>5.9</td>
<td>5.3</td>
<td>1.0</td>
<td>0.8</td>
</tr>
<tr class="even">
<td>Gomez_2016</td>
<td>32</td>
<td>30</td>
<td>4.8</td>
<td>4.2</td>
<td>1.2</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>Patel_2019</td>
<td>40</td>
<td>39</td>
<td>5.5</td>
<td>4.9</td>
<td>1.4</td>
<td>1.2</td>
</tr>
<tr class="even">
<td>Chen_2020</td>
<td>35</td>
<td>33</td>
<td>5.1</td>
<td>4.5</td>
<td>1.2</td>
<td>1.1</td>
</tr>
</tbody>
</table>
</section>
<section id="section-3" class="slide level2">
<h2></h2>
<p>The <strong>standardised mean difference (SMD)</strong> between e.g.&nbsp;restored and control sites is calculated as follows:</p>
<p><span class="math display">\[\text{SMD} = \frac{\text{mean}_{\text{restored}} - \text{mean}_{\text{control}}}{\text{pooled standard deviation}}\]</span> Where the <strong>pooled standard deviation</strong> is calculated as:</p>
<p><span class="math display">\[2SD_{\text{pooled}} = \sqrt{\frac{(n_{\text{restored}} - 1) \cdot SD_{\text{restored}}^2 + (n_{\text{control}} - 1) \cdot SD_{\text{control}}^2}{n_{\text{restored}} + n_{\text{control}} - 2}}\]</span></p>
</section>
<section id="effect-size-lnrr" class="slide level2">
<h2>Effect size LnRR</h2>
<ul>
<li>The <strong>log response ratio (LnRR)</strong> is another common effect size used in meta-analysis, particularly in ecology. It is calculated as:</li>
</ul>
<p><span class="math display">\[\text{LnRR} = \ln\left(\frac{\text{mean}_{\text{treatment}}}{\text{mean}_{\text{control}}}\right)\]</span></p>
<ul>
<li>The <strong>log response ratio</strong> is useful because it can handle ratios that are less than 1 (i.e., negative effects) and is symmetric around zero.</li>
</ul>
</section>
<section id="section-4" class="slide level2">
<h2></h2>
<p>Imagine a study comparing biodiversity in grazed vs.&nbsp;ungrazed grasslands:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Mean Biodiversity</th>
<th>Standard Deviation</th>
<th>Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grazed</td>
<td>15.2</td>
<td>2.5</td>
<td>30</td>
</tr>
<tr class="even">
<td>Ungrazed</td>
<td>18.6</td>
<td>3.1</td>
<td>28</td>
</tr>
</tbody>
</table>
<p>We calculate the effect size as: <span class="math display">\[\text{-0.202} = \ln\left(\frac{\text{15.2}}{\text{18.6}}\right)\]</span></p>
</section>
<section id="section-5" class="slide level2">
<h2></h2>
<p>Interpretation</p>
<ul>
<li><p>LnRR &gt; 0: Treatment increases the outcome</p></li>
<li><p>LnRR &lt; 0: Treatment decreases the outcome</p></li>
<li><p>LnRR ≈ 0: No effect</p></li>
<li><p>In our example, the negative LnRR suggests grazing reduces biodiversity in this study</p></li>
</ul>
</section>
<section id="variance" class="slide level2">
<h2>Variance</h2>
<ul>
<li><strong>Variance/weighting</strong> – <em>“More precise studies get more influence in the pooled estimate.”</em></li>
<li>In meta-analysis, not all studies are treated equally. Some studies provide more precise estimates than others, and variance (uncertainty) helps determine their weight in the overall analysis.</li>
</ul>
</section>
<section id="section-6" class="slide level2">
<h2></h2>
<ul>
<li>Each study reports an effect size (e.g., LnRR) and a measure of its uncertainty. The variance of an effect size is calculated as:</li>
</ul>
<p><span class="math display">\[v_i = \frac{SD_1^2}{n_1 \cdot \text{Mean}_1^2} + \frac{SD_2^2}{n_2 \cdot \text{Mean}_2^2}\]</span></p>
</section>
<section id="how-variance-affects-study-weighting" class="slide level2">
<h2>How Variance Affects Study Weighting</h2>
<ul>
<li><p>Studies with smaller variance (precise estimates, large sample size, low SD) get higher weight.</p></li>
<li><p>Studies with higher variance (uncertain estimates, small sample size, high SD) get lower weight.</p></li>
<li><p>In a random-effects meta-analysis, we also account for between-study heterogeneity (τ²), which represents true variation beyond sampling error.</p></li>
</ul>
</section>
<section id="section-7" class="slide level2">
<h2></h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>LnRR</th>
<th>Variance (vi)</th>
<th>Weight in Meta-Analysis</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study A (Large n, Low SD)</td>
<td>-0.20</td>
<td>0.01</td>
<td>High ✅</td>
<td></td>
</tr>
<tr class="even">
<td>Study B (Small n, High SD)</td>
<td>-0.20</td>
<td>0.10</td>
<td>Low ❌</td>
<td></td>
</tr>
</tbody>
</table>
<p>Even though both studies report the same effect size (-0.20), Study A gets more weight because it is more precise.</p>
</section>
<section id="fixed-vs.-random-effects" class="slide level2">
<h2>Fixed vs.&nbsp;random effects</h2>
<ul>
<li>In a fixed-effect model, we assume that all studies estimate the same true effect.</li>
<li>In contrast, a random-effects model assumes that each study estimates its own effect size, accounting for between-study variability.</li>
</ul>
</section>
<section id="fixed-effect" class="slide level2">
<h2>Fixed effect</h2>

<img data-src="images/clipboard-3554449211.png" class="r-stretch"></section>
<section id="random-effects" class="slide level2">
<h2>Random effects</h2>

<img data-src="images/clipboard-268787001.png" class="r-stretch"></section>
<section id="multi-level-models" class="slide level2">
<h2>Multi-level models</h2>
<ul>
<li>Accounts for hierarchical data structures
<ul>
<li>e.g.&nbsp;multiple sites for a single study or multiple measurements from one site</li>
<li>e.g.&nbsp;multiple studies on the same species or taxonomic groups</li>
</ul></li>
<li>Normally the method we use in ecology</li>
</ul>
</section>
<section id="section-8" class="slide level2">
<h2></h2>

<img data-src="images/clipboard-2459106515.png" class="r-stretch"></section>
<section id="heterogeneity---the-fun-part" class="slide level2">
<h2>Heterogeneity - the fun part!</h2>
<ul>
<li><p>Heterogeneity is one of the most critical aspects of meta-analysis—it tells us whether the effect sizes across studies are similar or highly variable.</p></li>
<li><p>Recognising and handling heterogeneity is essential for drawing reliable conclusions.</p></li>
<li><p>The expectation of heterogeneity is the main difference between medicine and ecology meta-analysis.</p></li>
</ul>
</section>
<section id="what-is-heterogeneity" class="slide level2">
<h2>What is Heterogeneity?</h2>
<ul>
<li>Heterogeneity refers to the variation in effect sizes across studies. If all studies estimate the same true effect, the only differences between them should be due to sampling error. However:
<ul>
<li>Biological &amp; ecological differences</li>
<li>Methodological differences</li>
<li>Publication effects</li>
</ul></li>
<li>When heterogeneity is high, a simple average of effect sizes may not be meaningful</li>
</ul>
</section>
<section id="understanding-the-outputs-from-a-meta-analysis" class="slide level2">
<h2>Understanding the outputs from a meta-analysis</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 10; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0128 (SE = 0.0071)
tau (square root of estimated tau^2 value):      0.1131
I^2 (total heterogeneity / total variability):   85.89%
H^2 (total variability / sampling variability):  7.09

Test for Heterogeneity:
Q(df = 9) = 58.1438, p-val &lt; .0001

Model Results:

estimate      se     zval    pval    ci.lb   ci.ub    
 -0.0593  0.0387  -1.5300  0.1260  -0.1352  0.0167    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="section-9" class="slide level2">
<h2></h2>
<ul>
<li><p>Random-Effects Model (k = 10; tau² estimator: REML)</p>
<ul>
<li>You are analysing 10 effect sizes (k = 10) using a random-effects model, meaning you assume each study is estimating a different but related true effect size</li>
<li>The REML (Restricted Maximum Likelihood) method is used to estimate between-study variance.</li>
</ul></li>
</ul>
</section>
<section id="between-study-variance" class="slide level2">
<h2>Between-Study Variance</h2>
<p><strong>tau² = 0.0128 (SE = 0.0071)</strong></p>
<p>This is the estimated amount of heterogeneity (real variation) in true effect sizes between studies.</p>
<p><em>Interpretation:</em></p>
<p>The larger this value, the more variation exists among study results beyond random sampling error. It’s in squared units of your effect size</p>
</section>
<section id="standard-deviation-of-true-effects" class="slide level2">
<h2>Standard Deviation of True Effects</h2>
<p><strong>tau = 0.1131</strong></p>
<p>This is simply the square root of tau². It gives the standard deviation of true effect sizes across studies.</p>
<p><em>Interpretation:</em> On average, true effect sizes vary by ~0.11 around the average effect size.</p>
</section>
<section id="proportion-of-variability-due-to-heterogeneity" class="slide level2">
<h2>Proportion of Variability Due to Heterogeneity</h2>
<p><strong>I² = 85.89%</strong></p>
<p>This tells you the percentage of total variability in effect sizes that is due to real differences between studies, rather than random chance.</p>
<p><em>Interpretation:</em> A very high I² (86%) means most of the variation is likely due to actual differences in study context (e.g., species, location, design) — not just sampling error.</p>
</section>
<section id="ratio-of-total-to-sampling-variability" class="slide level2">
<h2>Ratio of Total to Sampling Variability</h2>
<p><strong>H² = 7.09</strong> This tells you how much bigger the total variability is compared to what you’d expect from sampling error alone.</p>
<p><em>Interpretation:</em> The observed variability in effect sizes is about 7 times larger than what we’d expect if all studies were estimating the same true effect size.</p>
</section>
<section id="test-for-heterogeneity" class="slide level2">
<h2>Test for Heterogeneity</h2>
<p><strong>Q(df = 9) = 58.14, p &lt; .0001</strong></p>
<p>This is Cochran’s Q test, which tests if observed variability is more than expected by chance.</p>
<p><em>Interpretation:</em> Since the p-value is very small (&lt; 0.0001), we reject the null hypothesis of homogeneity.There is significant heterogeneity — studies are not all estimating the same effect.</p>
<p>⚠️ Caveat: The Q test can be overly sensitive with many studies, and underpowered with few.</p>
</section>
<section id="overall-effect-size-estimate" class="slide level2">
<h2>Overall Effect Size Estimate</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Estimate</th>
<th>SE</th>
<th>Z-value</th>
<th>p-value</th>
<th>CI (95%)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-0.0593</td>
<td>0.0387</td>
<td>-1.53</td>
<td>0.1260</td>
<td>-0.1352 to 0.0167</td>
<td></td>
</tr>
</tbody>
</table>
<p>Estimate: The average effect size is -0.0593.</p>
<p>CI includes 0, and p = 0.126, so the effect is not statistically significant at the 0.05 level.</p>
<p>This suggests there’s no consistent directional effect, but the high heterogeneity indicates the effects may differ across contexts.</p>
</section>
<section id="section-10" class="slide level2">
<h2></h2>
<p><code>In this meta-analysis, we found high heterogeneity (I² = 86%) among studies. This suggests that true effect sizes vary meaningfully across ecological contexts—perhaps due to different species, ecosystems, or study designs.The estimated average effect was small and not statistically significant, but given the variation across studies, this average may not be meaningful on its own.</code></p>
</section></section>
<section>
<section id="from-forest-plots-to-orchard-plots-visualising-meta-analysis-results" class="title-slide slide level1 center">
<h1>🌳 From Forest Plots to Orchard Plots 🍊: Visualising Meta-Analysis Results</h1>

</section>
<section id="forest-plots-the-classic-view" class="slide level2">
<h2>🌲 Forest Plots: The Classic View</h2>
<ul>
<li><p>Show individual study effect sizes with confidence intervals</p></li>
<li><p>Easy to interpret, especially for significance and precision</p></li>
<li><p>Great for small to moderate numbers of studies</p></li>
</ul>
<p>BUT… can get cluttered and hard to read with many studies or subgroup comparisons</p>
</section>
<section id="orchard-plots-a-modern-flexible-alternative" class="slide level2">
<h2>🍊 Orchard Plots: A Modern, Flexible Alternative</h2>
<ul>
<li>Summarise:
<ul>
<li>Study effect sizes (optionally grouped)</li>
<li>The overall model estimate (± CI)</li>
<li>Weighting of studies (as point size)</li>
</ul></li>
<li>Can show:
<ul>
<li>Meta-regression results</li>
<li>Multi-level models</li>
<li>Moderator effects</li>
</ul></li>
</ul>
</section>
<section id="section-11" class="slide level2">
<h2></h2>

<img data-src="Introduction_to_Meta-Analysis_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="section-12" class="slide level2">
<h2></h2>

<img data-src="Introduction_to_Meta-Analysis_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="regression-coefficients-as-effect-sizes" class="slide level2">
<h2>Regression Coefficients as Effect Sizes</h2>
<ul>
<li>Sometimes studies report <strong>regression coefficients</strong> instead of group comparisons.</li>
<li>These can be used directly as effect sizes if:
<ul>
<li>The predictor is consistent across studies (e.g., standardised)</li>
<li>The outcome is continuous</li>
</ul></li>
<li>Often extracted as <strong>raw slopes</strong>, <strong>standardised</strong> <span class="math inline">\(\beta\)</span>, or <strong>log-odds</strong></li>
</ul>
</section>
<section id="extracting-regression-coefficients" class="slide level2">
<h2>Extracting Regression Coefficients</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># Example: effect of temperature on bird abundance </span></span>
<span id="cb2-2"><a href=""></a></span>
<span id="cb2-3"><a href=""></a>study <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">study_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">yi =</span> <span class="fu">c</span>(<span class="fl">0.12</span>, <span class="fl">0.20</span>, <span class="fl">0.05</span>, <span class="fl">0.18</span>), <span class="co">#regression slopes </span></span>
<span id="cb2-4"><a href=""></a>                     <span class="at">sei =</span> <span class="fu">c</span>(<span class="fl">0.03</span>, <span class="fl">0.04</span>, <span class="fl">0.02</span>, <span class="fl">0.05</span>) )</span>
<span id="cb2-5"><a href=""></a></span>
<span id="cb2-6"><a href=""></a><span class="fu">rma</span>(yi, sei<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> study)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 4; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0038 (SE = 0.0041)
tau (square root of estimated tau^2 value):      0.0620
I^2 (total heterogeneity / total variability):   78.82%
H^2 (total variability / sampling variability):  4.72

Test for Heterogeneity:
Q(df = 3) = 15.4897, p-val = 0.0014

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.1297  0.0356  3.6405  0.0003  0.0599  0.1996  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="section-13" class="slide level2">
<h2></h2>
<ul>
<li>But must ensure effect direction is interpretable and consistent</li>
</ul>
</section>
<section id="standardising-predictors-or-outcomes" class="slide level2">
<h2>Standardising Predictors or Outcomes</h2>
<ul>
<li><p>If studies use different measurement scales:</p>
<ul>
<li><p><strong>Convert to standardised</strong> <span class="math inline">\(\beta\)</span> if possible</p></li>
<li><p>Or standardise both predictor and outcome before meta-analysis</p></li>
<li><p>Note: This can reduce heterogeneity and improve comparability</p></li>
</ul></li>
</ul>
</section>
<section id="standardising-regression-coefficients-beta" class="slide level2">
<h2>Standardising Regression Coefficients (<span class="math inline">\(\beta\)</span>)</h2>
<ul>
<li>Standardisation makes coefficients comparable across studies</li>
<li>Formula (for a simple linear regression):</li>
</ul>
<p><span class="math display">\[
\beta_{\text{standardised}} = \beta \cdot \frac{\text{SD}_X}{\text{SD}_Y}
\]</span></p>
</section>
<section id="section-14" class="slide level2">
<h2></h2>
<p>Where:</p>
<ul>
<li><p>(<span class="math inline">\(\beta\)</span>): unstandardised slope (from paper)</p></li>
<li><p>(<span class="math inline">\(\text{SD}\_X\)</span>): SD of predictor (e.g.&nbsp;temperature)</p></li>
<li><p>(<span class="math inline">\(\text{SD}\_Y\)</span>): SD of outcome (e.g.&nbsp;abundance)</p></li>
</ul>
</section>
<section id="example-temperature-effect-on-insect-abundance" class="slide level2">
<h2>Example: Temperature Effect on Insect Abundance</h2>
<p>Study reports: <span class="math inline">\(\beta\)</span> = 2.5 (per <span class="math inline">\(^\circ\)</span>C), temp SD = 5, abundance SD = 20</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>beta_raw <span class="ot">&lt;-</span> <span class="fl">2.5</span> </span>
<span id="cb4-2"><a href=""></a>sd_temp <span class="ot">&lt;-</span> <span class="dv">5</span> </span>
<span id="cb4-3"><a href=""></a>sd_abund <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb4-4"><a href=""></a>(beta_std <span class="ot">&lt;-</span> beta_raw <span class="sc">*</span> (sd_temp <span class="sc">/</span> sd_abund) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.625</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="co">#"A one SD increase in temperature is associated with a 0.625 SD increase in abundance."</span></span>
<span id="cb6-2"><a href=""></a></span>
<span id="cb6-3"><a href=""></a>studies <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">beta =</span> <span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">1.2</span>, <span class="fl">3.0</span>, <span class="fl">0.8</span>), <span class="at">sd_temp =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">3</span>), <span class="at">sd_abund =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">8</span>) )</span>
<span id="cb6-4"><a href=""></a>studies<span class="sc">$</span>beta_std <span class="ot">&lt;-</span> <span class="fu">with</span>(studies, beta <span class="sc">*</span> (sd_temp <span class="sc">/</span> sd_abund)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can now use beta_std as your yi values in rma() or rma.mv().</p>
</section>
<section id="section-15" class="slide level2">
<h2></h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Use SDs from within each study, not pooled</p>
</div>
</div>
</div>
<p>If variances (SE/CI) are available for raw <span class="math inline">\(\beta\)</span>, you can also transform the SEs: <span class="math display">\[SE std = SE raw * \frac{\text{SD}_X}{\text{SD}_Y}\]</span></p>
<ul>
<li>Check study assumptions: linearity, normality, scale units</li>
</ul>
</section>
<section id="funnel-plots-multi-level-meta-analysis" class="slide level2">
<h2>Funnel Plots &amp; Multi-Level Meta-Analysis</h2>
<ul>
<li><p>Traditional <strong>funnel plots</strong> assume <strong>independent effect sizes</strong></p></li>
<li><p>But in multilevel models, effects are nested (e.g., multiple per study)</p></li>
<li><p>This violates the assumption - misleading asymmetry or overdispersion</p></li>
</ul>
</section>
<section id="section-16" class="slide level2">
<h2></h2>

<img data-src="Introduction_to_Meta-Analysis_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"><ul>
<li><p>Visual inspection is unreliable</p></li>
<li><p>Needs a method that accounts for dependency</p></li>
</ul>
</section>
<section id="nakagawa-et-al.s-solution-2022" class="slide level2">
<h2>Nakagawa et al.’s Solution (2022)</h2>
<ul>
<li><p>Propose a <strong>regression-based test</strong> using residuals from multilevel model</p></li>
<li><p>Regress <strong>absolute residuals</strong> (or squared residuals) on precision</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>res <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(yi, vi, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> author, <span class="at">data =</span> dat) </span>
<span id="cb7-2"><a href=""></a>dat<span class="sc">$</span>resid <span class="ot">&lt;-</span> <span class="fu">resid</span>(res) </span>
<span id="cb7-3"><a href=""></a>dat<span class="sc">$</span>precision <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(dat<span class="sc">$</span>vi)  </span>
<span id="cb7-4"><a href=""></a><span class="fu">summary</span>(<span class="fu">lm</span>(<span class="fu">abs</span>(resid) <span class="sc">~</span> precision, <span class="at">data =</span> dat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = abs(resid) ~ precision, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.3511 -0.1793 -0.0032  0.1066  0.8765 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.50069    0.08253   6.067  2.3e-07 ***
precision   -0.04108    0.01540  -2.668   0.0105 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2418 on 46 degrees of freedom
Multiple R-squared:  0.134, Adjusted R-squared:  0.1151 
F-statistic: 7.116 on 1 and 46 DF,  p-value: 0.01051</code></pre>
</div>
</div>
<ul>
<li><p>A significant slope indicates funnel asymmetry (small-study effects)</p></li>
<li><p>Avoids misleading inferences from clustered data</p></li>
</ul>
</section>
<section id="advantages-of-residual-regression" class="slide level2">
<h2>Advantages of Residual Regression</h2>
<ul>
<li><p>Compatible with multi-level models</p></li>
<li><p>Avoids false positives in funnel asymmetry</p></li>
<li><p>Reproducible and testable in <code>R</code></p></li>
</ul>
</section>
<section id="recommended-literature" class="slide level2 smaller">
<h2>Recommended literature</h2>
<p>Sarkis-Onofre, R., Catal�-L�pez, F., Aromataris, E. et al.&nbsp;How to properly use the PRISMA Statement. Syst Rev 10, 117 (2021). https://doi.org/10.1186/s13643-021-01671-z</p>
<p>Nakagawa, S., Noble, D. W. A., Senior, A. M., &amp; Lagisz, M. (2017). Meta-evaluation of meta-analysis: ten appraisal questions for biologists. BMC Biology, 15(1), 18. https://doi.org/10.1186/s12915-017-0357-7Harrer, M., Cuijpers, P., Furukawa, T. A., &amp; Ebert, D. D. (2021). Doing Meta-Analysis With R: A Hands-On Guide (1st ed.). Chapman &amp; Hall/CRC Press. https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/Nakagawa, S., Lagisz, M., O’Dea, R. E., Pottier, P., Rutkowska, J., Senior, A. M., Yang, Y., &amp; Noble, D. W. A. (2023). orchaRd 2.0: An R package for visualising meta-analyses with orchard plots. Methods in Ecology and Evolution, 14(8), 2003-2010. https://doi.org/10.1111/2041-210x.14152</p>
<p>Coe, R. (2002). It’s the Effect Size - Stupid. Paper presented at the British Educational Research Association annual conference, Exeter, 12-14 September, 2002 https://f.hubspotusercontent30.net/hubfs/5191137/attachments/ebe/ESguide.pdf</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/JUNO_TAGLINE.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Introduction_to_Meta-Analysis_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>